# Generated by Django 3.0.3 on 2020-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_place_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_img',
        ),
        migrations.AddField(
            model_name='place',
            name='place_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
