# Generated by Django 3.0.3 on 2020-08-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200830_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('t_list', models.CharField(max_length=100)),
                ('t_description', models.CharField(max_length=500)),
                ('t_link', models.CharField(max_length=100)),
                ('t_map', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State')),
            ],
        ),
    ]
